repos:
  - repo: local
    hooks:
      - id: format-lint-and-test
        name: Format, Lint and Test
        entry: ./scripts/pre-commit-hook.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]