
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  influxdb:
    image: influxdb:2.7-alpine
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      # InfluxDB setup with sensible defaults
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-password123}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-system-monitor}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-telemetry}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION:-30d}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-dev-token-change-in-production}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    restart: unless-stopped
    command: ["web"]
    network_mode: "host"
    environment:
      # Django configuration
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-in-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      
      # Database configuration
      - DATABASE_URL=${DATABASE_URL:-sqlite:///db.sqlite3}
      
      # Redis configuration - uses localhost since we're on host network
      - REDIS_URL=${REDIS_URL:-redis://localhost:6379/0}
      
      # InfluxDB configuration - uses localhost since we're on host network
      - INFLUXDB_URL=${INFLUXDB_URL:-http://localhost:8086}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-dev-token-change-in-production}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-system-monitor}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-telemetry}
      
      # Agent configuration - can now reach localhost agent directly
      - AGENT_HOST=${AGENT_HOST:-127.0.0.1}
      - AGENT_PORT=${AGENT_PORT:-8000}
      - AGENT_BASE_URL=${AGENT_BASE_URL}
      
      # Agent polling configuration
      - AGENT_POLL_INTERVAL=${AGENT_POLL_INTERVAL:-1.0}
      - AGENT_TIMEOUT=${AGENT_TIMEOUT:-10.0}
      
      # Celery configuration - uses localhost since we're on host network
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://localhost:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://localhost:6379/0}
    
    depends_on:
      redis:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    
    volumes:
      - ./logs:/app/logs

volumes:
  redis_data:
  influxdb_data:
  influxdb_config: