name: Auto Merge CI

on:
  push:
    branches-ignore:
      - master

jobs:
  unit-tests:
    name: Unit Tests & Linting
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Setup development environment
      run: make dev
    
    - name: Run linting
      run: make lint
    
    - name: Run unit tests
      run: make test

  auto-merge:
    name: Auto-merge after delay
    needs: unit-tests
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Wait 5 minutes
      run: sleep 300
    
    - name: Create Pull Request and Auto-merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create \
          --title "Auto-merge: ${{ github.ref_name }}" \
          --body "Automated merge after unit tests and linting passed" \
          --base master \
          --head ${{ github.ref_name }}
        
        gh pr merge ${{ github.ref_name }} \
          --auto \
          --squash \
          --delete-branch